DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS password;

CREATE TABLE user (

  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL
  
);

CREATE TABLE password (

  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT,
  uname TEXT NOT NULL,
  upassword TEXT NOT NULL,
  url TEXT,
  notes TEXT,
  
  FOREIGN KEY (user_id) REFERENCES user (id)
  
);

